format="""
$directory\
$git_branch\
$git_status
$character"""

# add_newline = true

[character] 
success_symbol = '[➜](bold green)' 

[fill]
symbol = ' '

[directory]
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
format = 'on [$branch]($style) '	
# symbol = ''
style = 'bold purple'

[git_status]
format = '[$all_status$ahead_behind]($style)'

# add eval "$(starship init bash)" to bash.rc file
