format="""
$directory\
$git_branch\
$ocaml\
$python\
$character"""

[character] 
success_symbol = '[➜](bold green)' 

# ========== Dir ========== 

[directory]
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false
format = '[$path ]($style)'

# ========== Git ========== 

[git_branch]
style = 'bold purple'
format = '\([$branch]($style)\)'
# ignore_branches = ['master', 'main']

# ========== Languages ========== 

[ocaml]
style = 'bold yellow'
format = '[\($switch_indicator$switch_name\)]($style)'

[python]
style = 'bold white'
format = '[\($virtualenv\)]($style) '

# (add eval "$(starship init bash)" to bash.rc file)
